/* Copyright(C) 2017-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * server.js: homebridge-unifi-protect webUI server API.
 *
 * This module is heavily inspired by the homebridge-config-ui-x source code and borrows from both.
 * Thank you oznu for your contributions to the HomeKit world.
 */
"use strict";

import { ProtectClient, isDeviceAdopted, noopLog } from "unifi-protect";
import { featureOptionCategories, featureOptions } from "../dist/options.js";
import { HomebridgePluginUiServer } from "@homebridge/plugin-ui-utils";
import util from "node:util";

class PluginUiServer extends HomebridgePluginUiServer {

  errorInfo;

  constructor() {

    super();

    this.errorInfo = "";

    // Register getErrorMessage() with the Homebridge server API.
    this.#registerGetErrorMessage();

    // Register getDevices() with the Homebridge server API.
    this.#registerGetDevices();

    // Register getOptions() with the Homebridge server API.
    this.#registerGetOptions();

    this.ready();
  }

  // Register the getErrorMessage() webUI server API endpoint.
  #registerGetErrorMessage() {

    // Return the most recent error message generated by the Protect API.
    this.onRequest("/getErrorMessage", () => this.errorInfo);
  }

  // Register getDevices() with the Homebridge server API.
  #registerGetDevices() {

    // Retrieve the list of devices from a Protect controller to populate the feature options device picker.
    this.onRequest("/getDevices", async (controller) => {

      // Start each probe with a clean error slate so /getErrorMessage reflects only this attempt.
      this.errorInfo = "";

      // A quiet logging shim for the short-lived client: debug/info/warn stay silent (noopLog), while error captures the message so /getErrorMessage can surface the
      // most recent failure reason to the user. The v5 ProtectLogging signature is (message, ...parameters), so we spread the rest parameters into util.format.
      const log = { ...noopLog, error: (message, ...parameters) => {

        this.errorInfo = util.format(message, ...parameters);

        // eslint-disable-next-line no-console
        console.error(this.errorInfo);
      } };

      try {

        // Connect to the controller. v5's connect() performs login and the initial bootstrap atomically, throwing a typed error on failure; await using guarantees the
        // client and its realtime connection are disposed on every exit path. We disable the periodic refresh failsafe since this is a one-shot discovery probe.
        await using client = await ProtectClient.connect({ host: controller.address, log: log, password: controller.password, refreshIntervalMs: false,
          username: controller.username });

        // Sort adopted devices by display name, falling back to the market name when a device has no user-assigned name.
        const byName = (a, b) => (a.name ?? a.marketName).localeCompare(b.name ?? b.marketName);

        // Project each live device collection to its raw config record, keep only the devices adopted by this controller, and sort. We read the config records rather
        // than the command-bearing projections because the webUI consumes plain controller fields and serializes them across the request boundary.
        const adopted = (devices) => devices.map(device => device.config).filter(isDeviceAdopted).sort(byName);

        // Return the controller first, then the adopted devices by category. The controller is element 0 - the controller-as-device entry the feature options webUI
        // selects on initial load.
        return [ client.nvr.config, ...adopted(client.cameras), ...adopted(client.chimes), ...adopted(client.lights), ...adopted(client.sensors),
          ...adopted(client.viewers) ];
      } catch(error) {

        // The library reports failures through the log seam above; if it threw without logging, fall back to the thrown error's message so the user still sees a reason.
        this.errorInfo ||= (error instanceof Error) ? error.message : String(error);

        // eslint-disable-next-line no-console
        console.error(error);

        return [];
      }
    });
  }

  // Register the getOptions() webUI server API endpoint.
  #registerGetOptions() {

    // Return the list of options configured for a given Protect device.
    this.onRequest("/getOptions", () => ({ categories: featureOptionCategories, options: featureOptions }));
  }
}

(() => new PluginUiServer())();
